---
title: "R Notebook"
output: html_notebook
---
setwd("~/Documents/kekonom")
library(tidyverse) # манипуляции с данными
library(fable) # ETS, ARIMA, ...
library(feasts) # графики рядов и характеристики
library("ggplot2")  # построение графиков 
library("forcats")
library(rio) # импортировать данные из csv, xlsx, dta, eviews, ...
library(tsibble) # формат хранения рядов
library(lubridate) # работа с датами
library(readr)
library("car")
library(olsrr)
library(lmtest)
library("sandwich")

forestfires <- read_csv("forestfires.csv")
View(forestfires)

ff <- subset(forestfires, area != 0) # очистка от нулевых значений
summary(ff) # минимум, максимум, среднее, медиана всех переменных

jan <- ifelse(ff$month == 'jan', 1, 0)
feb <- ifelse(ff$month == 'feb', 1, 0)
mar <- ifelse(ff$month == 'mar', 1, 0)
apr <- ifelse(ff$month == 'apr', 1, 0)
may <- ifelse(ff$month == 'may', 1, 0)
jun <- ifelse(ff$month == 'jun', 1, 0)
jul <- ifelse(ff$month == 'jul', 1, 0)
aug <- ifelse(ff$month == 'aug', 1, 0)
sep <- ifelse(ff$month == 'sep', 1, 0)
oct <- ifelse(ff$month == 'oct', 1, 0)
nov <- ifelse(ff$month == 'nov', 1, 0)
dec <- ifelse(ff$month == 'dec', 1, 0) # введем дамми переменные на месяца года, вдруг пригодится

# рассмотрим переменные внимательнее на графиках

boxFFMC <- boxplot(ff$FFMC, col = 'greenyellow', main = "FFMC", sub = 'ящик с усами FFMC')
plot(density(ff$FFMC), main = 'FFMC Density') # изучив смысл данного коэффициента можно предположить, что он должен влиять положительно на зависимую переменную. Но в целом было сказано, что у этого коэффициента есть определенное "стандартное" значение выше 80. То есть отклонения ниже считаются скорее исключениями, поэтому можем рассмотреть включение этого коэффициента детальнее

boxDMC <- boxplot(ff$DMC, col = 'greenyellow', main = "DMC", sub = 'ящик с усами DMC')
plot(density(ff$DMC), main = 'DMC Density') # показывает "стресс" почвы, по смыслу коэффициента он должен влиять положительно и судя по графикам, он должен объяснять большую долю разброса

boxDC <- boxplot(ff$DC, col = 'greenyellow', main = "DC", sub = 'ящик с усами DC')
plot(density(ff$DC), main = 'DC Density') # коэф показывает на сколько сильно просохли почвы, по смыслу должен иметь положительный вклад, значения выше 800 говорят о критической ситуации, включим эту переменную в регрессию

boxISI <- boxplot(ff$ISI, col = 'greenyellow', main = "DISI", sub = 'ящик с усами ISI')
plot(density(ff$ISI), main = 'ISI Density') # переменная о распространеннии пожара, должна по смыслу иметь отрицательный вклад, судя по графикам ее стоит учесть

boxtemp <- boxplot(ff$temp, col = 'greenyellow', main = "temp", sub = 'усы температуры')
plot(density(ff$temp), main = 'temp Density') # из жизненного опыта температура должна положительно влиять на распространение пожаров и иметь достаточно значимую в этом роль. Из графиков видно, что плотность температуры имеет достаточно большой разброс и должна объяснять зависимую переменную хорошо.

boxRH <- boxplot(ff$RH, col = 'greenyellow', main = "RH", sub = 'ящик с усами RH')
plot(density(ff$RH), main = 'RH Density') # уровень влажности, колеблется в среднем около 40% с некоторыми высокими выбросами, из жизни коэффициент должен отрицательно влиять на пожары, включим в уравнение

boxwind <- boxplot(ff$wind, col = 'greenyellow', main = "wind", sub = 'ящик с усамиwind')
plot(density(ff$wind), main = 'Wind Density') # как известно, ветер хорошо разносит пожар и очень негативно сказывается на природе, сказываясь позитивно на распространении пожаров, включим в регресиию

boxrain <- boxplot(ff$rain, col = 'greenyellow', main = "rain", sub = 'ящик с усами дождя')
plot(density(ff$rain), main = 'Rain Density') # судя по графикам, этот показатель почти всегда принимает значение ноль. Включать его в регрессию нет смысла, поскольку он мало информацтивен

X <- model.matrix(~ 0 + FFMC + DMC + DC + ISI + temp + RH + wind, ff)
XX <- t(X) %*% X
eigen <- eigen(XX)
eigen$values  # считаем CI по методике Бориса Борисовича

CI <- sqrt(max(eigen$values) / min(eigen$values))
CI  # индекс обусловленности выше 30 (370) что говорито наличии МК

reg1 <- lm(area ~ FFMC + DMC + DC + ISI + temp + RH + wind, ff)
summary(reg1)

vif(reg1) # хотя подсчет VIF не говорит о наличии МК (?). Проверим через матрицу ковариаций

X <- model.matrix(~ 0 + FFMC + DMC + DC + ISI + temp + RH + wind, ff)
cor(X) # построим матрицу ковариаций. Заметим, что у cov(ISI, FFMC) > 0.7, cov(DMC, DC) > 0.66 можно сказать, что эти пары переенных сильно коррелируют между собой и могут порождать мультиколлинеарность

# бороться с МК можно убрав некоторые коррелирующие переменные. Тогда, выбирая из ISI и FFMC, я оставляю ISI (у него дисперсия выше и значимость в регресси больше). Выбирая между DMC и DC оставим DMC (значимость в регресии выше). Вообще, можно сазать что все коэффициенты очень высоко коррелируют с температурой, поэтому, также можно рассмотреть регрессию в которую не включается этот показатель

reg2 <- lm(area ~ DMC + ISI + temp + RH + wind, ff)
summary(reg2)
vif(reg2)

X2 <- model.matrix(~ 0 + DMC + ISI + temp + RH + wind, ff)
cor(X2) # корреляция между коэфициентами уже низкая!

XX2 <- t(X2) %*% X2
eigen2 <- eigen(XX2)
eigen2$values  

CI2 <- sqrt(max(eigen2$values) / min(eigen2$values))
CI2  # индекс обусловленности существенно ниже (71) но все еще выше порогового 30

reg3 <- lm(area ~ DMC + ISI + RH + wind, ff)
vif(reg3) # виф низкий, что говорит о том, что регрессоры плохо выражаются друг через друга, и нет мультиколлинеарности

X3 <- model.matrix(~ 0 + DMC + ISI + RH + wind, ff)
cor(X3) # выглядит хорошо

XX3 <- t(X3) %*% X3
eigen3 <- eigen(XX3)
eigen3$values  

CI3 <- sqrt(max(eigen3$values) / min(eigen3$values))
CI3  # индекс обусловленности почти не изменился, 70. Но значение все равно значительно лучше, чем было изначально. Можно сказать с МК поборолись. Хотя в целом можно было и не бороться и оставить широкие интервалы как есть.

X4 <- model.matrix(~ 0 + area + DMC + ISI + RH + wind, ff)
cor(X4) # а еще нет прямой корреляции с зависимой переменной, что тоже должно быть хорошо

# итак, у нас осталась регрессия на коэффициенты DMC ISI RH и wind. Исследуем ее
reg3 <- lm(area ~ DMC + ISI + RH + wind, ff)
summary(reg3) # коэффицинты DMC и RH стали значимыми на уровне значимости 5% и значимтельно улучшилась сама модель, P-value F-теста уже меньше 0.2, R-sq низкий, но нам это и не столь важно. 
# DMC (на сколько глубого просохли почвы) имеет коэф бета 0.16 (при росте показателя на 1 показатель area растет на 0.16) положительный как и ожидалось
# ISI (прогнозирует поведение и распространение огня в зависимости от увлажненности почвы, ветра и др.) коэф имеет отрицательный вклад. При росте этого показателя на 1, распространение пожара (area) снижается на 1.2
# RH (влажность воздуха) как и предполагалось имеет отрицательный вклад, при росте влажности на 1% (рост показателя на 1) снижмается зоня огня на 0.7
# ветер наоборот, вносит сильно положительный вклад. Остается только проблема с тем, что t test показывает незначимость коэффициентов wind и ISI (может потому что один коэффициент так или иначе включает в себя другой?)
# модель можно назвать значимосй на уровне значимости в 20% Этот уровень слишком высокий, чтобы говорить о том, что наша модель очень хороша.
# Также мною были рассмотрены модели, в которые включены дамми переменные месяцов, но в таких моделях R-adj даже был отрицательным, что говорит о том, что такие модели хуже некуда. Хотя теоретически, можно найти зависимость между месяцем и пожарами, например летом и осенью пожары намного более масштабнее. Возможно, это объясняется другими переменными, которые уже входят в модель

# исследуем на нормальность остатков. 

plot(density(ff$area), main = 'area Density')
hist(ff$area)

ols_test_normality(reg3) # p-value = 0 нулевая гипотеза отвергается, распределение не нормальное. Вообще, этот результат предсказуем, если посмотреть на гистограмму зависимой переменной, она как видно из графика мало похожа на номально распределенную

# построим средние оценки (на средних)
conf_interval <- predict(reg3, ffnew=ff.frame(DMC = 114.7, ISI = 9.177, RH=43.73, wind=4.113), interval="confidence", level = 0.95)
conf_interval

# индивидуальный интервал (на медианных)
ind_interval <- predict(reg3, ffnew=ff.frame(DMC = 111.7, ISI = 8.4, RH=41, wind=4), interval="prediction", level = 0.95)
ind_interval

# Точечные 
predict(reg3, ffnew=ff.frame(DMC = 111.7, ISI = 8.4, RH=41, wind=4))

# гетероскедатичность пораждается например когда переменные имеют разную размерность. Например wind, выраженный в км/ч прнимает значения от 0 до 9.4, а переменная DMC, безразмерная величина от 1.1 до 291.3. Таким образом, можно предположить, что гетероскедастичность порождает такая величина, как  DMC, остальные величины имеют не настолько существенный разброс, например RH в процентах колеблется от 15 до 100. То есть из-за разной размерности, dmc изменяется в абсолютном показателе значительнее, чем остальные переменные, 

# Проведет тест на ГС тестом Г-Кванта, отсортировав по параметру DMC. Нулевая гипотеза отвергается, подтверждается альтернативная, что дисперсия между двумя сегментами разная и действительно есть гетероскедастичность. Аналогично, произошло и с переменными ISI и wind. Но гетероскедастичность не вызвала переменная ISI

gqtest(reg3, order.by = ~DMC, data = ff)
gqtest(reg3, order.by = ~ISI, data = ff)
gqtest(reg3, order.by = ~RH, data = ff)
gqtest(reg3, order.by = ~wind, data = ff)

# для борьбы с ГС можно применить взвешенный МНК. Предположим ковариационная матрица ошибок диагональна. По методу Бориса Борисовича, предположим, что в нашем случае var(e|DMC) = const * DMC. Параметр весов делаем обратно пропорциональным дисперсиям.

reg4 <- lm( area ~ DMC + ISI + RH + wind, weights = I(1 / DMC), data =ff)
summary(reg4)

# после применения взвешенного мнк у нас упала значимость коэффициентов, теперь ни один не значим при ур значимости 10%, хотя немного выросла значимост всей модели  в целом.
#DMC  (стало) 0.112 <- 0.0765 (было)
#ISI         0.653 <- 0.3853
#RH          0.181 <- 0.0518
#wind         0.785 <- 0.5315

# поменялись даже коэффициенты, хотя этого теоретически не ожидалось
#DMC  (стало) 0.13010 <- 0.16357 (было)
#ISI         -0.50713 <- -1.19747
#RH          -0.29467 <- -0.70029
#wind         0.39061 <- 1.80273

# s errors сократились, чего и следовало ожидать
#DMC  (стало) 0.08148 <- 0.09196 (было)
#ISI         1.12720 <- 1.37694
#RH          0.21949 <- 0.35852
#wind         1.43046 <- 2.87755

# HC0 предполагает ковариационную матрицу ошибок такую, где на главное диагонали матрицы весов стоят квадраты остатков каждого уравнения. То есть мы оцениваем уравнение, вычитаем из y - y^крышку и возводим получившиеся остатки в квадрат. подставляем в диагональную матрицу весов. Ков матрица ошибок принимает вид (X′X)−1X′Ω̂ X(X′X)−1
# сейчас чаще используется HC3

vcovHC(reg3)
reg5 <- lm( area ~ DMC + ISI + RH + wind, vcov = vcovHC(reg3), data =ff)
summary(reg5)

# оценки вернули свою значимость и стали похожи на те, что были изначальн


